#!/usr/bin/env bash

# Grype Multi-Target Vulnerability Scanner
# Comprehensive vulnerability detection for containers, filesystems, and SBOMs

# Colors for help output
WHITE='\033[1;37m'
NC='\033[0m'

# Help function
show_help() {
    echo -e "${WHITE}Grype Multi-Target Vulnerability Scanner${NC}"
    echo ""
    echo "Usage: $0 [OPTIONS] [TARGET_DIRECTORY|SCAN_MODE]"
    echo ""
    echo "Comprehensive vulnerability detection for containers, filesystems, and SBOMs"
    echo "using Anchore's Grype scanner."
    echo ""
    echo "Arguments:"
    echo "  TARGET_DIRECTORY    Path to directory to scan (default: current directory)"
    echo "  SCAN_MODE           Scan mode: filesystem, images, base, or all (default: all)"
    echo ""
    echo "Options:"
    echo "  -h, --help          Show this help message and exit"
    echo ""
    echo "Environment Variables:"
    echo "  TARGET_DIR          Alternative way to specify target directory"
    echo "  SCAN_ID             Override auto-generated scan ID"
    echo "  SCAN_DIR            Override output directory for scan results"
    echo ""
    echo "Output:"
    echo "  Results are saved to: scans/{SCAN_ID}/grype/"
    echo "  - grype-filesystem-results.json    Filesystem vulnerabilities"
    echo "  - grype-sbom-results.json          SBOM-based vulnerabilities"
    echo "  - grype-scan.log                   Scan process log"
    echo ""
    echo "Scan Modes:"
    echo "  filesystem    Scan only the filesystem/directory"
    echo "  images        Scan container images from docker-compose"
    echo "  base          Scan base images only"
    echo "  all           Scan everything (default)"
    echo ""
    echo "Examples:"
    echo "  $0                              # Scan current directory (all modes)"
    echo "  $0 /path/to/project             # Scan specific directory"
    echo "  $0 filesystem                   # Filesystem scan only"
    echo "  TARGET_DIR=/app $0 images       # Scan container images"
    echo ""
    echo "Notes:"
    echo "  - Requires Docker to be installed and running"
    echo "  - Uses anchore/grype:latest Docker image"
    echo "  - Can scan SBOMs generated by Syft"
    exit 0
}

# Parse arguments
for arg in "$@"; do
    case $arg in
        -h|--help)
            show_help
            ;;
    esac
done

# Initialize scan environment using scan directory approach
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./common.sh
source "$SCRIPT_DIR/common.sh"
CONFIG_DIR="$(cd "$SCRIPT_DIR/../../configuration" && pwd)"

# Source the scan directory template
source "$SCRIPT_DIR/scan-directory-template.sh"

# Source container runtime detection utility if available
if [ -f "$SCRIPT_DIR/container-runtime.sh" ]; then
    # shellcheck source=/dev/null
    set +e
    source "$SCRIPT_DIR/container-runtime.sh"
    set -e
fi
if [ -z "${CONTAINER_CLI:-}" ]; then
    CONTAINER_CLI=docker
fi

# Source approved base images configuration only if PRIMARY_BASELINE_IMAGE is not already set
if [ -z "${PRIMARY_BASELINE_IMAGE:-}" ] && [ -f "$CONFIG_DIR/approved-base-images.conf" ]; then
    source "$CONFIG_DIR/approved-base-images.conf"
fi

# Initialize scan environment for Grype
init_scan_environment "grype"

# Set REPO_PATH and extract scan information
REPO_PATH="${1:-${TARGET_DIR:-$(pwd)}}"
# Handle special scan type keywords
if [[ "$REPO_PATH" == "filesystem" ]] || [[ "$REPO_PATH" == "images" ]] || [[ "$REPO_PATH" == "base" ]]; then
    SCAN_MODE="$REPO_PATH"
    REPO_PATH="${TARGET_DIR:-$(pwd)}"
else
    SCAN_MODE="all"
fi
REPO_PATH=$(realpath "${REPO_PATH}" 2>/dev/null) || { echo "ERROR: Target path does not exist or is invalid: ${REPO_PATH}" >&2; exit 1; }
if [[ -n "$SCAN_ID" ]]; then
    TARGET_NAME=$(echo "$SCAN_ID" | cut -d'_' -f1)
    USERNAME=$(echo "$SCAN_ID" | cut -d'_' -f2)
    TIMESTAMP=$(echo "$SCAN_ID" | cut -d'_' -f3-)
else
    # Fallback for standalone execution
    TARGET_NAME=$(basename "$REPO_PATH")
    USERNAME=$(whoami)
    TIMESTAMP=$(date '+%Y-%m-%d_%H-%M-%S')
    SCAN_ID="${TARGET_NAME}_${USERNAME}_${TIMESTAMP}"
fi

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
NC='\033[0m' # No Color

echo -e "${WHITE}============================================${NC}"
echo -e "${WHITE}Grype Multi-Target Vulnerability Scanner${NC}"
echo -e "${WHITE}============================================${NC}"
echo "Repository: $REPO_PATH"
echo "Output Directory: $OUTPUT_DIR"
echo "Timestamp: $TIMESTAMP"
echo

# Display file count for transparency
if [ -d "$REPO_PATH" ]; then
    TOTAL_FILES=$(count_scannable_files "$REPO_PATH" "*")
    echo -e "${CYAN}📊 Target Analysis:${NC}"
    echo -e "   📁 Target Directory: $REPO_PATH"
    echo -e "   📄 Total Files to Scan: $TOTAL_FILES"
    get_file_breakdown "$REPO_PATH"
    echo
fi

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Initialize scan log
echo "Grype scan started: $TIMESTAMP" > "$SCAN_LOG"
echo "Target: $REPO_PATH" >> "$SCAN_LOG"

# Prefer local Grype binary; fall back to Docker
LOCAL_GRYPE=""
if command -v grype >/dev/null 2>&1; then
    LOCAL_GRYPE="$(command -v grype)"
    echo -e "${GREEN}✅ Using local Grype installation: $(grype version 2>/dev/null | head -1)${NC}"
    echo "Using local Grype: $LOCAL_GRYPE" >> "$SCAN_LOG"
    # Update local vulnerability database
    echo -e "${CYAN}📥 Updating Grype vulnerability database...${NC}"
    grype db update 2>&1 | tee -a "$SCAN_LOG" || true
else
    # Create persistent volume for Grype cache to speed up subsequent scans
    GRYPE_CACHE_VOL="grype-cache"
    ${CONTAINER_CLI} volume create "$GRYPE_CACHE_VOL" 2>/dev/null || true

    # Update Grype vulnerability database before scanning
    echo -e "${CYAN}📥 Updating Grype vulnerability database...${NC}"
    echo "This ensures we have the latest CVE data (may take 1-2 minutes on first run)..."

    ${CONTAINER_CLI} run --rm \
        -e GRYPE_DB_CACHE_DIR=/cache \
        -v "$GRYPE_CACHE_VOL:/cache" \
        anchore/grype:latest \
        db update 2>&1 | tee -a "$SCAN_LOG"
fi

DB_UPDATE_RESULT=$?
if [ $DB_UPDATE_RESULT -eq 0 ]; then
    echo -e "${GREEN}✅ Grype vulnerability database updated successfully${NC}"
else
    echo -e "${YELLOW}⚠️  Database update had issues (exit code: $DB_UPDATE_RESULT)${NC}"
    echo "   Proceeding with cached database..."
fi

# Show database info
echo -e "${CYAN}📋 Checking Grype database status...${NC}"
${CONTAINER_CLI} run --rm \
    -e GRYPE_DB_CACHE_DIR=/cache \
    -v "$GRYPE_CACHE_VOL:/cache" \
    anchore/grype:latest \
    db status 2>&1 | tee -a "$SCAN_LOG"
echo

# Function to run Grype scan
run_grype_scan() {
    local scan_type="$1"
    local target="$2"
    local output_file="$OUTPUT_DIR/${SCAN_ID}_grype-${scan_type}-results.json"
    local current_file="$OUTPUT_DIR/grype-${scan_type}-results.json"

    echo -e "${BLUE}🔍 Scanning ${scan_type}: ${target}${NC}"

    local scan_ok=false
    if [ -n "$LOCAL_GRYPE" ]; then
        echo "   Using local Grype binary..."
        if [[ "$scan_type" == "base-"* ]] || [[ "$target" == *":"* ]]; then
            "$LOCAL_GRYPE" "$target" -o json 2>>"$SCAN_LOG" > "$output_file"
        else
            "$LOCAL_GRYPE" "dir:$target" -o json 2>>"$SCAN_LOG" > "$output_file"
        fi
        [ $? -eq 0 ] && [ -s "$output_file" ] && scan_ok=true
    elif [ -n "${CONTAINER_CLI:-}" ]; then
        echo "   Using ${CONTAINER_CLI}-based Grype..."
        if [[ "$scan_type" == "base-"* ]] || [[ "$target" == *":"* ]]; then
            ${CONTAINER_CLI} run --rm \
                -e GRYPE_DB_CACHE_DIR=/cache \
                -v /var/run/docker.sock:/var/run/docker.sock \
                -v "$GRYPE_CACHE_VOL:/cache" \
                anchore/grype:latest \
                "docker:$target" -o json 2>>"$SCAN_LOG" > "$output_file"
        else
            ${CONTAINER_CLI} run --rm \
                -e GRYPE_DB_CACHE_DIR=/cache \
                -v "$target:/workspace:ro" \
                -v "$GRYPE_CACHE_VOL:/cache" \
                anchore/grype:latest \
                dir:/workspace -o json 2>>"$SCAN_LOG" > "$output_file"
        fi
        [ $? -eq 0 ] && [ -s "$output_file" ] && scan_ok=true
    fi

    if $scan_ok; then
        local count=$(jq '.matches | length' "$output_file" 2>/dev/null || echo "0")
        echo -e "${GREEN}   ✅ ${scan_type} scan completed: $count vulnerabilities found${NC}"
        echo "${scan_type} scan: $count vulnerabilities" >> "$SCAN_LOG"
        ln -sf "$(basename "$output_file")" "$current_file" 2>/dev/null
    else
        echo -e "${RED}   ❌ ${scan_type} scan failed or produced no output${NC}"
        echo "${scan_type} scan: FAILED" >> "$SCAN_LOG"
        echo '{"matches": [], "source": {"type": "directory", "target": "'"$target"'"}}' > "$output_file"
    fi
    echo
}

# Determine scan type based on first argument
SCAN_TYPE="${1:-all}"

echo -e "${CYAN}🔍 Step 1: Vulnerability Detection${NC}"
echo "=================================="

# Run SBOM-based scan (preferred method - uses pre-generated SBOM)
if [[ "$SCAN_TYPE" == "sbom" ]] || [[ "$SCAN_TYPE" == "all" ]]; then
    # Look for SBOM file from environment or standard location
    # Prefer CycloneDX SBOM for grype (richer format with better vuln matching)
    SBOM_FILE="${SBOM_FILE:-$SCAN_DIR/sbom/filesystem.json}"
    _CDX=$(find "${SCAN_DIR:-}/sbom" -maxdepth 1 \( -name "filesystem-cyclonedx.json" -o -name "*.cyclonedx.json" \) 2>/dev/null | head -1)
    [ -n "$_CDX" ] && SBOM_FILE="$_CDX"

    if [ -f "$SBOM_FILE" ]; then
        echo -e "${GREEN}📋 Using SBOM-based vulnerability scan (recommended)${NC}"
        echo "   SBOM file: $SBOM_FILE"

        output_file="$OUTPUT_DIR/${SCAN_ID}_grype-sbom-results.json"
        current_file="$OUTPUT_DIR/grype-sbom-results.json"

        sbom_ok=false
        if [ -n "$LOCAL_GRYPE" ]; then
            echo -e "${BLUE}🔍 Scanning SBOM for vulnerabilities (local grype)...${NC}"
            "$LOCAL_GRYPE" "sbom:$SBOM_FILE" -o json 2>>"$SCAN_LOG" > "$output_file"
            [ $? -eq 0 ] && [ -s "$output_file" ] && sbom_ok=true
        elif [ -n "${CONTAINER_CLI:-}" ]; then
            echo -e "${BLUE}🔍 Scanning SBOM for vulnerabilities...${NC}"
            ${CONTAINER_CLI} run --rm \
                -e GRYPE_DB_CACHE_DIR=/cache \
                -v "$SBOM_FILE:/sbom.json:ro" \
                -v "$GRYPE_CACHE_VOL:/cache" \
                anchore/grype:latest \
                sbom:/sbom.json -o json 2>>"$SCAN_LOG" > "$output_file"
            [ $? -eq 0 ] && [ -s "$output_file" ] && sbom_ok=true
        fi

        if $sbom_ok; then
            sbom_count=$(jq '.matches | length' "$output_file" 2>/dev/null || echo "0")
            echo -e "${GREEN}   ✅ SBOM scan completed: $sbom_count vulnerabilities found${NC}"
            echo "SBOM scan: $sbom_count vulnerabilities" >> "$SCAN_LOG"
            ln -sf "$(basename "$output_file")" "$current_file" 2>/dev/null
        else
            echo -e "${RED}   ❌ SBOM scan failed${NC}"
            echo '{"matches": [], "source": {"type": "sbom", "target": "'"$SBOM_FILE"'"}}' > "$output_file"
        fi
    else
        echo -e "${YELLOW}⚠️ SBOM file not found: $SBOM_FILE${NC}"
        echo "   Falling back to filesystem scan..."
        # Fall back to filesystem scan if no SBOM
        if [ -d "$REPO_PATH" ]; then
            run_grype_scan "filesystem" "$REPO_PATH"
        fi
    fi
fi

# Run filesystem scan only if explicitly requested (not for "all" anymore - SBOM is preferred)
if [[ "$SCAN_TYPE" == "filesystem" ]]; then
    if [ -d "$REPO_PATH" ]; then
        run_grype_scan "filesystem" "$REPO_PATH"
    else
        echo "⚠️  Target directory not found: $REPO_PATH"
    fi
fi

# Run image scans for "images" or "all"
if [[ "$SCAN_TYPE" == "images" ]] || [[ "$SCAN_TYPE" == "all" ]]; then
    # Use PRIMARY_BASELINE_IMAGE if set by orchestrator, otherwise use configuration
    if [ -n "${PRIMARY_BASELINE_IMAGE:-}" ]; then
        IMAGES_TO_SCAN=("${PRIMARY_BASELINE_IMAGE}")
        echo -e "${CYAN}📋 Using user-selected baseline image${NC}"
    elif [ ${#APPROVED_BASE_IMAGES[@]} -gt 0 ]; then
        IMAGES_TO_SCAN=("${APPROVED_BASE_IMAGES[@]}")
        echo -e "${CYAN}📋 Using ${#IMAGES_TO_SCAN[@]} approved base images${NC}"
    else
        # Fallback to Docker Hardened Image
        IMAGES_TO_SCAN=("dhi/caddy:debian-13-2-fips-dev@sha256:ba86d16733750c6fd7b8866981016d2479e234c842d77413f1bf41c4404e555c")
    fi
    
    for image in "${IMAGES_TO_SCAN[@]}"; do
        echo -e "${BLUE}📦 Scanning base image: $image${NC}"
        if [ -n "${CONTAINER_CLI:-}" ]; then
            # Check if image exists locally first
            if ${CONTAINER_CLI} image inspect "$image" &>/dev/null; then
                echo "   ✅ Using cached image"
            else
                echo "   ⏬ Pulling image..."
                if ! ${CONTAINER_CLI} pull "$image" >> "$SCAN_LOG" 2>&1; then
                    echo "   ⚠️ Pull failed - skipping this image"
                    continue
                fi
            fi
            run_grype_scan "base-$(echo $image | tr ':/' '-')" "$image"
        fi
    done
fi

# Count results
RESULTS_COUNT=$(find "$OUTPUT_DIR" -name "grype-*-results.json" -type f | wc -l | tr -d ' ')

echo
echo -e "${CYAN}📊 Grype Vulnerability Summary${NC}"
echo "==============================="
echo "📄 Results files generated: $RESULTS_COUNT"

# Basic results summary
echo -e "🔍 Vulnerability Detection Summary:"
if [ "$RESULTS_COUNT" -gt 0 ]; then
    echo -e "${YELLOW}⚠️  $RESULTS_COUNT result files found - review recommended${NC}"
    echo "Results saved to: $OUTPUT_DIR"
    
    # Simple vulnerability count using jq if available
    if command -v jq &> /dev/null; then
        total_vulns=0
        for file in "$OUTPUT_DIR"/grype-*-results.json; do
            if [ -f "$file" ]; then
                count=$(jq '.matches | length' "$file" 2>/dev/null || echo 0)
                total_vulns=$((total_vulns + count))
            fi
        done
        echo "Total vulnerabilities found: $total_vulns"
    fi
else
    echo -e "${GREEN}✅ No vulnerabilities detected${NC}"
fi

echo
echo -e "${BLUE}📁 Output Files:${NC}"
echo "================"
for file in "$OUTPUT_DIR"/grype-*-results.json; do
    if [ -f "$file" ]; then
        echo "📄 $(basename "$file")"
    fi
done
for file in "$OUTPUT_DIR"/sbom-*.json; do
    if [ -f "$file" ]; then
        echo "📦 $(basename "$file")"
    fi
done
echo "📝 Scan log: $SCAN_LOG"
echo "📂 Reports directory: $OUTPUT_DIR"

echo
echo -e "${BLUE}🔧 Available Commands:${NC}"
echo "===================="
echo "📊 Analyze results:        npm run grype:analyze"
echo "🔍 Run new scan:           npm run grype:scan"
echo "🏗️  Filesystem only:        ./run-grype-scan.sh filesystem"
echo "📦 Images only:            ./run-grype-scan.sh images"
echo "📋 View specific results:  cat $OUTPUT_DIR/grype-*-results.json | jq ."

echo
echo -e "${BLUE}🔗 Additional Resources:${NC}"
echo "======================="
echo "• Grype Documentation: https://github.com/anchore/grype"
echo "• Vulnerability Management: https://owasp.org/www-project-top-ten/2017/A9_2017-Using_Components_with_Known_Vulnerabilities"
echo "• Container Security: https://kubernetes.io/docs/concepts/security/"

echo
echo "============================================"
echo -e "${GREEN}✅ Grype vulnerability detection completed!${NC}"
echo "============================================"
echo
echo "============================================"
echo "Grype vulnerability scanning complete."
echo "============================================"